name: Check code quality on pull request

on:
  pull_request:
  workflow_dispatch:

env:
  SONAR_HOST_URL: https://sonarcloud.io
  SONAR_PROJECT_KEY: sonarqube-quality-gate-action

jobs:
  sonar-scan:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=phwt
            -Dsonar.projectKey=sonarqube-quality-gate-action
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.branch.name=feature/branches

      - name: Wait quality gate result
        run: sleep 5

      - name: Create a comment with the result
        uses: ./
        id: quality-gate-check
        with:
          sonar-host-url: ${{ env.SONAR_HOST_URL }}
          sonar-project-key: ${{ env.SONAR_PROJECT_KEY }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/branches # TODO: use value from the PR branch

      - run: |
          echo "${{ steps.quality-gate-check.outputs.project-status }}"
          echo "${{ steps.quality-gate-check.outputs.quality-gate-result }}"
